apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret
  namespace: chat-app
type: Opaque
data:
  jwt: ZTM5MjQxNzlmYWEyYjVhZTdlMTU2ZDE2ZDEzNmJjOTMzYTliODVhNmNmYjM5ZDUxYjRjYWEzNDkwMjNmMmQ4YzkxNjNmNzgzNTAyNGNlNWM4ZmQ0NmExYTE3MGQyNGU1NDAyNWFiNTQ2OTc4YzU5ZGFkNmEzNjIxYWIxNjAwOTU=
