apiVersion: v1
kind: Service
metadata:
  name: backend          # ← must match what nginx.conf expects
  namespace: chat-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001        # ← was 5001, must be 5000
      targetPort: 5001
  type: ClusterIP